services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-auth-template
    ports:
      - '3000:3000'
    command: sh -c "npx prisma db push && npm run start:prod"
    environment:
      PORT: 3000
      JWT_SECRET: hello_change_on_prod
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/chat_autigest?schema=public
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: nest-auth-template-db
    environment:
      POSTGRES_DB: nest-auth-template
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d chat_autigest']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
